name: foodiet
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 

  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/home1.jpg
    - assets/images/home2.jpg
    - assets/images/home3.jpg
    - assets/images/about.jpg
    - assets/images/wow1.jpg
    - assets/images/wow2.jpg
    - assets/images/wow3.jpg
    - assets/images/wow4.jpg
    - assets/images/wow5.jpg
    - assets/images/wow6.jpg
    - assets/images/wow7.jpg
    - assets/images/wow8.jpg
    - assets/images/wow9.jpg
    - assets/images/wow10.jpg
    - assets/images/wow11.jpg
    - assets/images/wow12.jpg
    - assets/images/wow13.jpg
    - assets/images/wow14.jpg
    - assets/images/wow15.jpg
    - assets/images/wow16.jpg
    - assets/images/wow17.jpg
    - assets/images/wow18.jpg
    - assets/images/wow19.jpg
    - assets/images/wow20.jpg
    - assets/images/wow21.jpg
    - assets/images/jenisdiet/d1.jpg
    - assets/images/jenisdiet/d2.jpg
    - assets/images/jenisdiet/d3.jpg
    - assets/images/jenisdiet/d4.jpg
    - assets/images/jenisdiet/d5.jpg
    - assets/images/jenisdiet/d6.jpg
    - assets/images/jenisdiet/d7.jpg
    - assets/images/jenisdiet/d8.jpg
    - assets/images/jenisdiet/d9.jpg
    - assets/images/jenisdiet/d10.jpg
    - assets/images/jenisdiet/d11.jpg
    - assets/images/jenisdiet/d12.jpg
    - assets/images/jenisdiet/d13.jpeg
    - assets/images/jenisdiet/d14.jpg
    - assets/images/jenisdiet/d15.jpg
    - assets/images/jenisdiet/d16.jpeg
    
    - data_repo/starwars_data.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
